# Predefined repair setups so they can be re-used later
RepairConfigs:
- &EasySoftware
    canBeRepairedByRemote: true
    canBeRepairedInFlight: true
    canBeRepairedOnSplashed: true
    dataScale: 1
    dataSize: 1
    repairChance: 75
- &MediumHydraulic
    canBeRepairedByRemote: false
    canBeRepairedInFlight: false
    canBeRepairedOnSplashed: false
    repairChance: 50
    replacementPart: 'HydraulicGizmo'
    replacementPartOptional: true
    replacementPartBonus: 0.10
- &EasyMechanical
    canBeRepairedByRemote: false
    canBeRepairedInFlight: false
    canBeRepairedOnSplashed: false
    repairChance: 75
FailureConfigs:
- &Explode
    failureTitle: 'Explosion!'
    failureType: 'mechanical'
    duFail: 400
    severity: 'major'
- &ResourceLeak_LiquidFuel
    failureTitle: 'Liquid Fuel Leaking'
    failureType: 'mechanical'
    duFail: 25
    duRepair: 50
    severity: 'failure'
    resourceToLeak: 'LiquidFuel'
    initialAmount: 10
    perSecondAmount: 1
- &ResourceLeak_Oxidizer
    failureTitle: 'Oxidizer Leaking'
    failureType: 'mechanical'
    duFail: 25
    duRepair: 50
    severity: 'failure'
    resourceToLeak: 'Oxidizer'
    initialAmount: 10
    perSecondAmount: 1
- &ResourceLeak_MonoPropellant
    failureTitle: 'MonoPropellant Leaking'
    failureType: 'mechanical'
    duFail: 25
    duRepair: 50
    severity: 'failure'
    resourceToLeak: 'MonoPropellant'
    initialAmount: 1
    perSecondAmount: 0.1
- &ResourceLeak_Random
    failureTitle: 'Tank is leaking'
    failureType: 'mechanical'
    duFail: 25
    duRepair: 50
    severity: 'failure'
    resourceToLeak: 'random'
    initialAmount: 5
    perSecondAmount: 1
PartConfigs:
    # Solids
    HighReliabilityTank: &HRTank
        # Should only ever be ONE Interop module for a unique PART in KSP.
        -   name: 'TestFlightInterop'
        -   name: 'TestFlightCore'
            maxData: 10000
        -   name: 'FlightDataRecorder_Resources'
            flightDataMultiplier: 10
            flightDataEngineerModifier: 0.25
        -   name: 'TestFlightReliability'
            reliabilityCurve:
                - '0 0.00015'
                - '10000 0.00002'
        # When referencing a block like this for use in a module, the blocks have to come BEFORE the module itself.  They will then get folded down into it
        -   *ResourceLeak_Random
        -   name: 'TestFlightFailure_ResourceLeak'
            weight: 32
        -   *Explode
        -   name: 'TestFlightFailure_Explode'
            weight: 2
    StartingTank: &StartTank
        # Should only ever be ONE Interop module for a unique PART in KSP.
        -   name: 'TestFlightInterop'
        -   name: 'TestFlightCore'
            maxData: 10000
            startFlightData: 10000
        -   name: 'FlightDataRecorder_Resources'
            flightDataMultiplier: 10
            flightDataEngineerModifier: 0.25
        -   name: 'TestFlightReliability'
            reliabilityCurve:
                - '0 0.00015'
                - '10000 0.00002'
        # When referencing a block like this for use in a module, the blocks have to come BEFORE the module itself.  They will then get folded down into it
        -   *ResourceLeak_Random
        -   name: 'TestFlightFailure_ResourceLeak'
            weight: 32
        -   *Explode
        -   name: 'TestFlightFailure_Explode'
            weight: 2
Parts:
-   part: 'ResourceTank'
    patterns:
    - '@PART[*]:HAS[@RESOURCE[*]]:FINAL'
    configs:
    - *HRTank
